/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.resume.panel;

import com.mycompany.dao.inter.SkillDaoInter;
import com.mycompany.dao.inter.UserSkillDaoInter;
import com.mycompany.entity.Skill;
import com.mycompany.entity.UserSkill;
import com.mycompany.main.Context;
import com.mycompany.resume.config.Config;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class PanelSkills extends javax.swing.JPanel {

    Config config = Config.creatConfig();
    SkillDaoInter skillDao = Context.instanceSkillDao();
    UserSkillDaoInter userSkillDao = Context.instanceUserSkillDao();

    /**
     * Creates new form SkillsPanel
     */
    public PanelSkills() {
        initComponents();

    }

    private void fillWindow() {
        config.setSkills(skillDao.getAll());
        cbSkills.removeAllItems();
        for (Skill s : config.getSkills()) {
            cbSkills.addItem(s);
        }
    }

    public void fillUserComponents() {
        fillWindow();
        int userID = config.getLoggedInUser().getId();
        List<UserSkill> uSkills = userSkillDao.getAllSkillByUserId(userID);
        config.getLoggedInUser().setSkills(uSkills);
        Vector<Vector> rows = new Vector<>();
        for (UserSkill s : uSkills) {
            Vector<Object> row = new Vector<>();
            row.add(s.getSkill());
            row.add(s.getLevel());
            rows.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(rows, new Vector<String>(Arrays.asList("Skill", "Level")));
        tblSkills.setModel(dtm);
    }

    public void saveBtn() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSkills = new javax.swing.JPanel();
        pnlSkillsControl = new javax.swing.JPanel();
        cbSkills = new javax.swing.JComboBox<>();
        lblSkill = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        sldrLevel = new javax.swing.JSlider();
        txtSkill = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        pnlSkillTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSkills = new javax.swing.JTable();

        lblSkill.setText("Skill");

        lblLevel.setText("Level");

        sldrLevel.setMaximum(10);
        sldrLevel.setPaintLabels(true);
        sldrLevel.setPaintTicks(true);
        sldrLevel.setToolTipText("");
        sldrLevel.setValue(0);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSkillsControlLayout = new javax.swing.GroupLayout(pnlSkillsControl);
        pnlSkillsControl.setLayout(pnlSkillsControlLayout);
        pnlSkillsControlLayout.setHorizontalGroup(
            pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSkillsControlLayout.createSequentialGroup()
                        .addComponent(lblLevel)
                        .addGap(18, 18, 18)
                        .addComponent(sldrLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                        .addComponent(lblSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(txtSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)))
                .addGap(8, 8, 8))
        );
        pnlSkillsControlLayout.setVerticalGroup(
            pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbSkills)
                    .addComponent(txtSkill)
                    .addComponent(lblSkill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                        .addComponent(lblLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addComponent(sldrLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate))
                .addContainerGap())
        );

        tblSkills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblSkills);

        javax.swing.GroupLayout pnlSkillTableLayout = new javax.swing.GroupLayout(pnlSkillTable);
        pnlSkillTable.setLayout(pnlSkillTableLayout);
        pnlSkillTableLayout.setHorizontalGroup(
            pnlSkillTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSkillTableLayout.setVerticalGroup(
            pnlSkillTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSkillsLayout = new javax.swing.GroupLayout(pnlSkills);
        pnlSkills.setLayout(pnlSkillsLayout);
        pnlSkillsLayout.setHorizontalGroup(
            pnlSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSkillsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlSkillsControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSkillTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSkillsLayout.setVerticalGroup(
            pnlSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSkillsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSkillTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlSkillsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(pnlSkillsControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSkills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSkills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String skillName = txtSkill.getText();
        Skill skill = null;
        if (skillName != null && !skillName.isEmpty()) {
            skill = new Skill(null, skillName);
            skillDao.add(skill);
        } else {
            skill = (Skill) cbSkills.getSelectedItem();
        }
        int level = sldrLevel.getValue();
        UserSkill us = new UserSkill(null, config.getLoggedInUser(), skill, level);
        userSkillDao.add(us);
        fillUserComponents();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int index = tblSkills.getSelectedRow();
        if (index >= 0) {
            List<UserSkill> userSkills = config.getLoggedInUser().getSkills();
            int userSkillId = userSkills.get(index).getSkill().getId();
            userSkillDao.delete(userSkillId);
        }
        fillUserComponents();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int index = tblSkills.getSelectedRow();
        int level = sldrLevel.getValue();
        String skillName = txtSkill.getText();
        Skill skill = null;

        if (index >= 0) {
            if (skillName != null && !skillName.isEmpty()) {
                skill = new Skill(null, skillName);
                skillDao.add(skill);
            } else {
                skill = (Skill) cbSkills.getSelectedItem();
            }
            List<UserSkill> userSkills = config.getLoggedInUser().getSkills();
            UserSkill userSkill = userSkills.get(index);
            userSkill.setLevel(level);
            userSkill.setSkill(skill);
            userSkillDao.update(userSkill);
            fillUserComponents();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Skill> cbSkills;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblSkill;
    private javax.swing.JPanel pnlSkillTable;
    private javax.swing.JPanel pnlSkills;
    private javax.swing.JPanel pnlSkillsControl;
    private javax.swing.JSlider sldrLevel;
    private javax.swing.JTable tblSkills;
    private javax.swing.JTextField txtSkill;
    // End of variables declaration//GEN-END:variables
}
