/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.resume.panel;

import com.mycompany.dao.inter.SkillDaoInter;
import com.mycompany.entity.Skill;
import com.mycompany.main.Context;
import com.mycompany.resume.config.Config;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class PanelSkills extends javax.swing.JPanel {
    Config config = Config.creatConfig();
    SkillDaoInter skillDao = Context.instanceSkillDao();
    /**
     * Creates new form SkillsPanel
     */
    public PanelSkills() {
        initComponents();
    }
    
    private void fillWindow(){
        config.setSkills(skillDao.getAll());
        for(Skill s: config.getSkills()){
            cbSkills.addItem(s.getName());
        }
    }
    
    public void fillUserComponents(){
        fillWindow();
        config.getLoggedInUser().getSkills();
        
        
    }
    
    public void saveBtn(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSkills = new javax.swing.JPanel();
        pnlSkillsControl = new javax.swing.JPanel();
        cbSkills = new javax.swing.JComboBox<>();
        lblSkill = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        sldrLevel = new javax.swing.JSlider();
        txtSkill = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        pnlSkillTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSkills = new javax.swing.JTable();

        cbSkills.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSkill.setText("Skill");

        lblLevel.setText("Level");

        sldrLevel.setMaximum(10);
        sldrLevel.setMinimum(1);
        sldrLevel.setPaintLabels(true);
        sldrLevel.setPaintTicks(true);
        sldrLevel.setToolTipText("");
        sldrLevel.setValue(1);

        btnDelete.setText("Delete");

        btnAdd.setText("Add");

        javax.swing.GroupLayout pnlSkillsControlLayout = new javax.swing.GroupLayout(pnlSkillsControl);
        pnlSkillsControl.setLayout(pnlSkillsControlLayout);
        pnlSkillsControlLayout.setHorizontalGroup(
            pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                        .addGroup(pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(txtSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnDelete))
                            .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                                .addComponent(lblSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSkillsControlLayout.createSequentialGroup()
                        .addComponent(lblLevel)
                        .addGap(18, 18, 18)
                        .addComponent(sldrLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlSkillsControlLayout.setVerticalGroup(
            pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillsControlLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSkill)
                    .addComponent(txtSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLevel)
                    .addComponent(sldrLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSkillsControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        tblSkills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblSkills);

        javax.swing.GroupLayout pnlSkillTableLayout = new javax.swing.GroupLayout(pnlSkillTable);
        pnlSkillTable.setLayout(pnlSkillTableLayout);
        pnlSkillTableLayout.setHorizontalGroup(
            pnlSkillTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSkillTableLayout.setVerticalGroup(
            pnlSkillTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSkillsLayout = new javax.swing.GroupLayout(pnlSkills);
        pnlSkills.setLayout(pnlSkillsLayout);
        pnlSkillsLayout.setHorizontalGroup(
            pnlSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSkillsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSkillsControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSkillTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSkillsLayout.setVerticalGroup(
            pnlSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSkillTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSkillsControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSkills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSkills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cbSkills;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblSkill;
    private javax.swing.JPanel pnlSkillTable;
    private javax.swing.JPanel pnlSkills;
    private javax.swing.JPanel pnlSkillsControl;
    private javax.swing.JSlider sldrLevel;
    private javax.swing.JTable tblSkills;
    private javax.swing.JTextField txtSkill;
    // End of variables declaration//GEN-END:variables
}
